Repository WildCodeSchool/tours-0320-php-elbaja-boxing-academy, pull requests merged in 2020-06, with the labels that each got.

#6 Navbar
  README.md
  assets/fonts/BOXING- striped.ttf
  assets/fonts/BOXING.otf
  assets/fonts/BOXING.ttf
  assets/fonts/Graduate-Regular.ttf
  assets/images/logoEBA.jpg
  assets/js/app.js
  assets/scss/_vars.scss
  assets/scss/app.scss
  assets/scss/home.scss
  assets/scss/navbarfooter.scss
  config/routes.yaml
  package.json
  src/Controller/HomeController.php
  templates/base.html.twig
  templates/footer.html.twig
  templates/home.html.twig
  templates/navbar.html.twig
  webpack.config.js
  yarn.lock
Labels: Correction done

#7 Creation of entities
  .gitignore
  README.md
  composer.json
  composer.lock
  src/Entity/Event.php
  src/Entity/Member.php
  src/Entity/Project.php
  src/Migrations/Version20200602110346.php
  src/Migrations/Version20200602110959.php
  src/Migrations/Version20200602111447.php
  src/Migrations/Version20200602163539.php
  src/Repository/EventRepository.php
  src/Repository/MemberRepository.php
  src/Repository/ProjectRepository.php
  symfony.lock
Labels: Reviewed

#8 création page accueil
  assets/images/home_boxer_1.png
  assets/images/home_boxer_2.png
  assets/images/home_boxer_3.png
  assets/images/home_join_us.jpg
  assets/images/home_trainer.jpg
  assets/scss/app.scss
  assets/scss/home.scss
  package.json
  templates/home.html.twig
  yarn.lock
Labels: Proofreading

#9 PAGE PRINCE DU RING
  assets/images/home/home_boxer_1.png
  assets/images/home/home_boxer_2.png
  assets/images/home/home_boxer_3.png
  assets/images/home/home_join_us.jpg
  assets/images/home/home_trainer.jpg
  assets/images/prince/prince_2017.jpg
  assets/images/prince/prince_2018.jpg
  assets/images/prince/prince_2019.png
  assets/images/prince/prince_boxeur.jpg
  assets/scss/app.scss
  assets/scss/home.scss
  assets/scss/prince.scss
  config/routes.yaml
  src/Controller/HomeController.php
  templates/base.html.twig
  templates/footer.html.twig
  templates/home.html.twig
  templates/navbar.html.twig
  templates/prince.html.twig
  webpack.config.js
Labels: Reviewed

#10 Event crud/html/css
  .gitignore
  assets/images/event/event_gala1.jpeg
  assets/images/event/event_gala2.jpg
  assets/images/event/event_gala3.jpg
  assets/images/event/event_gala4.jpeg
  assets/scss/app.scss
  assets/scss/event.scss
  src/Controller/EventController.php
  src/Form/EventType.php
  templates/base.html.twig
  templates/event/_delete_form.html.twig
  templates/event/_form.html.twig
  templates/event/edit.html.twig
  templates/event/index.html.twig
  templates/event/new.html.twig
  templates/event/show.html.twig
  templates/footer.html.twig
  templates/home.html.twig
  templates/navbar.html.twig
Labels: Correction done, Proofreading

#11 Ajout connection en tant qu'Admin
  assets/scss/app.scss
  assets/scss/login.scss
  assets/scss/navbarfooter.scss
  composer.json
  composer.lock
  config/bundles.php
  config/packages/security.yaml
  config/routes.yaml
  src/Controller/HomeController.php
  src/Controller/SecurityController.php
  src/DataFixtures/AppFixtures.php
  src/DataFixtures/UserFixtures.php
  src/Entity/User.php
  src/Migrations/Version20200608085817.php
  src/Repository/UserRepository.php
  src/Security/LoginFormAuthenticator.php
  symfony.lock
  templates/home/prince.html.twig
  templates/navbar.html.twig
  templates/security/login.html.twig
  templates/security/profile.html.twig
Labels: Proofreading, Reviewed

#15 Event html/css
  assets/images/backgroundEBA.jpg
  assets/images/event/event_gala5.jpeg
  assets/images/event/event_gala6.jpg
  assets/scss/event.scss
  src/Form/EventType.php
  templates/event/edit.html.twig
  templates/event/index.html.twig
  templates/event/new.html.twig
  templates/event/show.html.twig
Labels: Reviewed

#14 Page partenaire
  assets/images/partenaire/century21.png
  assets/images/partenaire/creditAgricole.png
  assets/images/partenaire/polytech.jpeg
  assets/scss/app.scss
  assets/scss/partners.scss
  config/routes.yaml
  src/Controller/HomeController.php
  templates/home/partners.html.twig
  templates/navbar.html.twig
Labels: Reviewed

#18 correction bug navbar, page prince, path prince, route homecontroller
  assets/scss/event.scss
  assets/scss/partners.scss
  src/Controller/HomeController.php
  templates/event/index.html.twig
  templates/home/partners.html.twig
  templates/navbar.html.twig
Labels: Reviewed

#23 Page erreur 404
  assets/scss/app.scss
  assets/scss/error.scss
  composer.json
  composer.lock
  config/bundles.php
  src/Controller/HomeController.php
  symfony.lock
  templates/base.html.twig
  templates/bundles/TwigBundle/Exception/error.html.twig
  templates/bundles/TwigBundle/Exception/error403.html.twig
  templates/bundles/TwigBundle/Exception/error404.html.twig
Labels: Proofreading, Reviewed

#20 Ajout controller Prince et ajout CRUD Projet
  assets/images/logo/logoTours.png
  assets/images/project/project_1.jpg
  assets/scss/app.scss
  assets/scss/project.scss
  config/packages/twig.yaml
  config/routes.yaml
  src/Controller/HomeController.php
  src/Controller/PrinceController.php
  src/Controller/ProjectController.php
  src/Form/ProjectType.php
  templates/footer.html.twig
  templates/index.html.twig
  templates/navbar.html.twig
  templates/prince/index.html.twig
  templates/project/_delete_form.html.twig
  templates/project/_form.html.twig
  templates/project/edit.html.twig
  templates/project/index.html.twig
  templates/project/new.html.twig
  templates/project/show.html.twig
  templates/security/login.html.twig
Labels: Reviewed

#24 Page event show
  assets/images/gant_background.jpg
  assets/scss/event.scss
  composer.json
  composer.lock
  config/packages/translation.yaml
  config/packages/twig.yaml
  config/packages/twig_extensions.yaml
  src/Entity/Event.php
  src/Form/EventType.php
  src/Migrations/Version20200616190357.php
  src/Migrations/Version20200617144937.php
  symfony.lock
  templates/event/_delete_form.html.twig
  templates/event/_form.html.twig
  templates/event/edit.html.twig
  templates/event/index.html.twig
  templates/event/new.html.twig
  templates/event/show.html.twig
  yarn.lock
Labels: Correction done

#27 responsive updated
  assets/scss/event.scss
  assets/scss/navbarfooter.scss
  assets/scss/prince.scss
  templates/navbar.html.twig
  templates/prince/index.html.twig
Labels: Proofreading, Reviewed

#25 Securisation des routes
  assets/scss/project.scss
  config/packages/easy_admin.yaml
  config/packages/security.yaml
  src/Controller/ProjectController.php
  src/Controller/SecurityController.php
  src/Controller/UserAdminController.php
  src/Security/LoginFormAuthenticator.php
  templates/navbar.html.twig
  templates/project/_delete_form.html.twig
  templates/project/_form.html.twig
  templates/project/edit.html.twig
  templates/project/index.html.twig
  templates/project/new.html.twig
  templates/project/show.html.twig
  templates/security/profile.html.twig
Labels: Reviewed

#31 Modification partners
  assets/scss/app.scss
  assets/scss/partner.scss
  assets/scss/partners.scss
  src/Controller/HomeController.php
  src/Controller/PartnerController.php
  src/Entity/Partner.php
  src/Form/PartnerType.php
  src/Migrations/Version20200602110346.php
  src/Migrations/Version20200602110959.php
  src/Migrations/Version20200602111447.php
  src/Migrations/Version20200602163539.php
  src/Migrations/Version20200608085817.php
  src/Migrations/Version20200618151853.php
  src/Repository/PartnerRepository.php
  templates/home/partners.html.twig
  templates/navbar.html.twig
  templates/partner/_delete_form.html.twig
  templates/partner/_form.html.twig
  templates/partner/edit.html.twig
  templates/partner/index.html.twig
  templates/partner/new.html.twig
  templates/partner/show.html.twig
Labels: Proofreading, Reviewed

#33 Modification partners
  assets/scss/app.scss
  assets/scss/partner.scss
  assets/scss/partners.scss
  src/Controller/HomeController.php
  src/Controller/PartnerController.php
  src/Entity/Partner.php
  src/Form/PartnerType.php
  src/Migrations/Version20200602110346.php
  src/Migrations/Version20200602110959.php
  src/Migrations/Version20200602111447.php
  src/Migrations/Version20200602163539.php
  src/Migrations/Version20200608085817.php
  src/Migrations/Version20200618151853.php
  src/Repository/PartnerRepository.php
  templates/home/partners.html.twig
  templates/navbar.html.twig
  templates/partner/_delete_form.html.twig
  templates/partner/_form.html.twig
  templates/partner/edit.html.twig
  templates/partner/index.html.twig
  templates/partner/new.html.twig
  templates/partner/show.html.twig
Labels: Proofreading, Reviewed

#35 First admin
  README.md
  assets/scss/app.scss
  assets/scss/partner.scss
  assets/scss/project.scss
  assets/scss/register.scss
  src/Controller/EventController.php
  src/Controller/RegistrationController.php
  src/Controller/SecurityController.php
  src/Form/UserType.php
  symfony.lock
  templates/base.html.twig
  templates/event/index.html.twig
  templates/event/show.html.twig
  templates/home/partners.html.twig
  templates/partner/index.html.twig
  templates/partner/show.html.twig
  templates/project/index.html.twig
  templates/registration/register_admin.html.twig
Labels: Correction done
